INSERT INTO berater_leagues (id, name, tier, category, country, tm_competition_url, is_active) VALUES
('OBLB', 'Oberliga Baden-Württemberg', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-baden-wurttemberg/startseite/wettbewerb/OBLB', true),
('OLB1', 'Bayernliga Nord', 5, 'herren', 'DE', 'https://www.transfermarkt.de/bayernliga-nord/startseite/wettbewerb/OLB1', true),
('OLB2', 'Bayernliga Süd', 5, 'herren', 'DE', 'https://www.transfermarkt.de/bayernliga-sud/startseite/wettbewerb/OLB2', true),
('OBLK', 'Bremenliga', 5, 'herren', 'DE', 'https://www.transfermarkt.de/bremenliga/startseite/wettbewerb/OBLK', true),
('OBLJ', 'Oberliga Hamburg', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-hamburg/startseite/wettbewerb/OBLJ', true),
('OBLC', 'Hessenliga', 5, 'herren', 'DE', 'https://www.transfermarkt.de/hessenliga/startseite/wettbewerb/OBLC', true),
('OLMR', 'Mittelrheinliga', 5, 'herren', 'DE', 'https://www.transfermarkt.de/mittelrheinliga/startseite/wettbewerb/OLMR', true),
('OLNI', 'Oberliga Niederrhein', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-niederrhein/startseite/wettbewerb/OLNI', true),
('OBLN', 'Oberliga Niedersachsen', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-niedersachsen/startseite/wettbewerb/OBLN', true),
('OBLF', 'NOFV-Oberliga Nord', 5, 'herren', 'DE', 'https://www.transfermarkt.de/nofv-oberliga-nord/startseite/wettbewerb/OBLF', true),
('OBLG', 'NOFV-Oberliga Süd', 5, 'herren', 'DE', 'https://www.transfermarkt.de/nofv-oberliga-sud/startseite/wettbewerb/OBLG', true),
('OLRP', 'Oberliga Rheinland-Pfalz/Saar', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-rheinland-pfalz-saar/startseite/wettbewerb/OLRP', true),
('OBLL', 'Oberliga Schleswig-Holstein', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-schleswig-holstein/startseite/wettbewerb/OBLL', true),
('OLW3', 'Oberliga Westfalen', 5, 'herren', 'DE', 'https://www.transfermarkt.de/oberliga-westfalen/startseite/wettbewerb/OLW3', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, country = EXCLUDED.country, tm_competition_url = EXCLUDED.tm_competition_url, is_active = EXCLUDED.is_active;

INSERT INTO berater_clubs (league_id, tm_club_id, club_name, tm_squad_url, is_active) VALUES
('OBLB', '1193', 'Bahlinger SC', 'https://www.transfermarkt.de/bahlinger-sc/kader/verein/1193', true),
('OBLB', '582', 'Karlsruher SC II', 'https://www.transfermarkt.de/karlsruher-sc-ii/kader/verein/582', true),
('OBLB', '834', 'TSG Balingen', 'https://www.transfermarkt.de/tsg-balingen/kader/verein/834', true),
('OBLB', '1203', 'FC Nöttingen', 'https://www.transfermarkt.de/fc-nottingen/kader/verein/1203', true),
('OBLB', '10780', 'FV Ravensburg', 'https://www.transfermarkt.de/fv-ravensburg/kader/verein/10780', true),
('OBLB', '12540', 'TSV Essingen', 'https://www.transfermarkt.de/tsv-essingen/kader/verein/12540', true),
('OBLB', '8354', 'SV Oberachern', 'https://www.transfermarkt.de/sv-oberachern/kader/verein/8354', true),
('OBLB', '30006', '1.CfR Pforzheim', 'https://www.transfermarkt.de/1-cfr-pforzheim/kader/verein/30006', true),
('OBLB', '68', 'SSV Reutlingen 05', 'https://www.transfermarkt.de/ssv-reutlingen-05/kader/verein/68', true),
('OBLB', '951', 'FC 08 Villingen', 'https://www.transfermarkt.de/fc-08-villingen/kader/verein/951', true),
('OBLB', '6830', 'TSG Backnang', 'https://www.transfermarkt.de/tsg-backnang/kader/verein/6830', true),
('OBLB', '74880', 'Türkischer SV Singen', 'https://www.transfermarkt.de/turkischer-sv-singen/kader/verein/74880', true),
('OBLB', '3466', '1.FC Normannia Gmünd', 'https://www.transfermarkt.de/1-fc-normannia-gmund/kader/verein/3466', true),
('OBLB', '58541', 'Türkspor Neckarsulm', 'https://www.transfermarkt.de/turkspor-neckarsulm/kader/verein/58541', true),
('OBLB', '35202', '1.FC Mühlhausen', 'https://www.transfermarkt.de/1-fc-muhlhausen/kader/verein/35202', true),
('OBLB', '2983', 'FC Teningen', 'https://www.transfermarkt.de/fc-teningen/kader/verein/2983', true),
('OBLB', '36975', 'Young Boys Reutlingen', 'https://www.transfermarkt.de/tsg-young-boys-reutlingen/kader/verein/36975', true),
('OBLB', '31865', 'FC Holzhausen', 'https://www.transfermarkt.de/fc-holzhausen/kader/verein/31865', true),
('OLB1', '7681', 'FC Ingolstadt 04 II', 'https://www.transfermarkt.de/fc-ingolstadt-04-ii/kader/verein/7681', true),
('OLB1', '565', 'SV Viktoria Aschaffenburg', 'https://www.transfermarkt.de/sv-viktoria-aschaffenburg/kader/verein/565', true),
('OLB1', '2552', 'SSV Jahn Regensburg II', 'https://www.transfermarkt.de/ssv-jahn-regensburg-ii/kader/verein/2552', true),
('OLB1', '40919', 'DJK Gebenbach', 'https://www.transfermarkt.de/djk-gebenbach/kader/verein/40919', true),
('OLB1', '1142', 'ASV Neumarkt', 'https://www.transfermarkt.de/asv-neumarkt/kader/verein/1142', true),
('OLB1', '1222', 'ASV Cham', 'https://www.transfermarkt.de/asv-cham/kader/verein/1222', true),
('OLB1', '1694', 'FC Eintracht Bamberg', 'https://www.transfermarkt.de/fc-eintracht-bamberg/kader/verein/1694', true),
('OLB1', '2278', 'SpVgg SV Weiden', 'https://www.transfermarkt.de/spvgg-sv-weiden/kader/verein/2278', true),
('OLB1', '8980', 'SV Fortuna Regensburg', 'https://www.transfermarkt.de/sv-fortuna-regensburg/kader/verein/8980', true),
('OLB1', '248', 'SpVgg Bayern Hof', 'https://www.transfermarkt.de/spvgg-bayern-hof/kader/verein/248', true),
('OLB1', '11708', 'TSV Neudrossenfeld', 'https://www.transfermarkt.de/tsv-neudrossenfeld/kader/verein/11708', true),
('OLB1', '18488', 'TSV Kornburg', 'https://www.transfermarkt.de/tsv-kornburg/kader/verein/18488', true),
('OLB1', '564', 'Würzburger FV 04', 'https://www.transfermarkt.de/wurzburger-fv/kader/verein/564', true),
('OLB1', '5526', 'FSV Stadeln', 'https://www.transfermarkt.de/fsv-stadeln/kader/verein/5526', true),
('OLB1', '1613', 'TSV Nördlingen', 'https://www.transfermarkt.de/tsv-nordlingen/kader/verein/1613', true),
('OLB1', '6718', 'DJK Ammerthal', 'https://www.transfermarkt.de/djk-ammerthal/kader/verein/6718', true),
('OLB1', '27193', 'DJK Don Bosco Bamberg', 'https://www.transfermarkt.de/djk-don-bosco-bamberg/kader/verein/27193', true),
('OLB1', '1140', 'TSV Großbardorf', 'https://www.transfermarkt.de/tsv-grossbardorf/kader/verein/1140', true),
('OLB2', '73', 'TSV 1860 München II', 'https://www.transfermarkt.de/tsv-1860-munchen-ii/kader/verein/73', true),
('OLB2', '8336', 'SpVgg Hankofen-Hailing', 'https://www.transfermarkt.de/spvgg-hankofen-hailing/kader/verein/8336', true),
('OLB2', '24235', 'SV Kirchanschöring', 'https://www.transfermarkt.de/sv-kirchanschoring/kader/verein/24235', true),
('OLB2', '3515', 'FC Gundelfingen', 'https://www.transfermarkt.de/fc-gundelfingen/kader/verein/3515', true),
('OLB2', '18636', 'SV Erlbach', 'https://www.transfermarkt.de/sv-erlbach/kader/verein/18636', true),
('OLB2', '4191', 'FC Pipinsried', 'https://www.transfermarkt.de/fc-pipinsried/kader/verein/4191', true),
('OLB2', '1238', 'SV Heimstetten', 'https://www.transfermarkt.de/sv-heimstetten/kader/verein/1238', true),
('OLB2', '11586', 'FC Deisenhofen', 'https://www.transfermarkt.de/fc-deisenhofen/kader/verein/11586', true),
('OLB2', '64162', 'FC Sportfreunde Schwaig', 'https://www.transfermarkt.de/fc-sportfreunde-schwaig/kader/verein/64162', true),
('OLB2', '5146', 'TuS Geretsried', 'https://www.transfermarkt.de/tus-geretsried/kader/verein/5146', true),
('OLB2', '1216', 'FC Ismaning', 'https://www.transfermarkt.de/fc-ismaning/kader/verein/1216', true),
('OLB2', '9624', 'SV Schalding-Heining', 'https://www.transfermarkt.de/sv-schalding-heining/kader/verein/9624', true),
('OLB2', '6749', 'TSV Kottern-St. Mang', 'https://www.transfermarkt.de/tsv-kottern-st-mang/kader/verein/6749', true),
('OLB2', '303', 'SpVgg Landshut', 'https://www.transfermarkt.de/spvgg-landshut/kader/verein/303', true),
('OLB2', '74', 'TSV Schwabmünchen', 'https://www.transfermarkt.de/tsv-schwabmunchen/kader/verein/74', true),
('OLB2', '1246', 'TSV 1860 Rosenheim', 'https://www.transfermarkt.de/tsv-1860-rosenheim/kader/verein/1246', true),
('OLB2', '18638', 'TSV 1880 Wasserburg', 'https://www.transfermarkt.de/tsv-1880-wasserburg/kader/verein/18638', true),
('OLB2', '32869', 'FSV Pfaffenhofen', 'https://www.transfermarkt.de/fsv-pfaffenhofen/kader/verein/32869', true),
('OBLK', '9029', 'Blumenthaler SV', 'https://www.transfermarkt.de/blumenthaler-sv/kader/verein/9029', true),
('OBLK', '26444', 'SV Hemelingen', 'https://www.transfermarkt.de/sv-hemelingen/kader/verein/26444', true),
('OBLK', '9471', 'OSC Bremerhaven', 'https://www.transfermarkt.de/osc-bremerhaven/kader/verein/9471', true),
('OBLK', '20391', 'TV Eiche Horn', 'https://www.transfermarkt.de/tv-eiche-horn/kader/verein/20391', true),
('OBLK', '6322', 'Brinkumer SV', 'https://www.transfermarkt.de/brinkumer-sv/kader/verein/6322', true),
('OBLK', '10362', 'BTS Neustadt', 'https://www.transfermarkt.de/bts-neustadt/kader/verein/10362', true),
('OBLK', '6780', 'FC Union 60 Bremen', 'https://www.transfermarkt.de/fc-union-60-bremen/kader/verein/6780', true),
('OBLK', '8997', 'SV Werder Bremen III', 'https://www.transfermarkt.de/sv-werder-bremen-iii/kader/verein/8997', true),
('OBLK', '115', 'FC Oberneuland', 'https://www.transfermarkt.de/fc-oberneuland/kader/verein/115', true),
('OBLK', '45280', 'ESC Geestemünde', 'https://www.transfermarkt.de/esc-geestemunde/kader/verein/45280', true),
('OBLK', '9470', 'Leher TS Bremerhaven', 'https://www.transfermarkt.de/leher-ts-bremerhaven/kader/verein/9470', true),
('OBLK', '16346', 'SG Aumund-Vegesack', 'https://www.transfermarkt.de/sg-aumund-vegesack/kader/verein/16346', true),
('OBLK', '9469', 'KSV Vatan Sport', 'https://www.transfermarkt.de/ksv-vatan-sport/kader/verein/9469', true),
('OBLK', '6263', 'TS Woltmershausen', 'https://www.transfermarkt.de/ts-woltmershausen/kader/verein/6263', true),
('OBLK', '18328', 'TuS Schwachhausen', 'https://www.transfermarkt.de/tus-schwachhausen/kader/verein/18328', true),
('OBLK', '9035', 'SV Grohn', 'https://www.transfermarkt.de/sv-grohn/kader/verein/9035', true),
('OBLJ', '29049', 'Eintracht Norderstedt II', 'https://www.transfermarkt.de/eintracht-norderstedt-ii/kader/verein/29049', true),
('OBLJ', '298', 'Altona 93', 'https://www.transfermarkt.de/altona-93/kader/verein/298', true),
('OBLJ', '18887', 'ETSV Hamburg', 'https://www.transfermarkt.de/etsv-hamburg/kader/verein/18887', true),
('OBLJ', '907', 'TuS Dassendorf', 'https://www.transfermarkt.de/tus-dassendorf/kader/verein/907', true),
('OBLJ', '431', 'SC Victoria Hamburg', 'https://www.transfermarkt.de/sc-victoria-hamburg/kader/verein/431', true),
('OBLJ', '6150', 'USC Paloma Hamburg', 'https://www.transfermarkt.de/usc-paloma-hamburg/kader/verein/6150', true),
('OBLJ', '8759', 'HT 16 Hamburg', 'https://www.transfermarkt.de/ht-16-hamburg/kader/verein/8759', true),
('OBLJ', '14361', 'FC Teutonia 05 Ottensen', 'https://www.transfermarkt.de/fc-teutonia-05-ottensen/kader/verein/14361', true),
('OBLJ', '6233', 'FC Süderelbe', 'https://www.transfermarkt.de/fc-suderelbe/kader/verein/6233', true),
('OBLJ', '3417', 'Niendorfer TSV', 'https://www.transfermarkt.de/niendorfer-tsv/kader/verein/3417', true),
('OBLJ', '2538', 'TSV Sasel', 'https://www.transfermarkt.de/tsv-sasel/kader/verein/2538', true),
('OBLJ', '3861', 'TuRa Harksheide', 'https://www.transfermarkt.de/tura-harksheide/kader/verein/3861', true),
('OBLJ', '2636', 'TSV Buchholz 08', 'https://www.transfermarkt.de/tsv-buchholz-08/kader/verein/2636', true),
('OBLJ', '1478', 'HEBC Hamburg', 'https://www.transfermarkt.de/hebc-hamburg/kader/verein/1478', true),
('OBLJ', '1266', 'SC V/W Billstedt', 'https://www.transfermarkt.de/sc-v-w-billstedt/kader/verein/1266', true),
('OBLJ', '24733', 'SSG Nikola Tesla Hamburg', 'https://www.transfermarkt.de/ssg-nikola-tesla-hamburg/kader/verein/24733', true),
('OBLJ', '1054', 'Concordia Hamburg', 'https://www.transfermarkt.de/concordia-hamburg/kader/verein/1054', true),
('OBLJ', '8078', 'TBS Pinneberg', 'https://www.transfermarkt.de/tbs-pinneberg/kader/verein/8078', true),
('OBLC', '6508', 'SV Hummetroth', 'https://www.transfermarkt.de/sv-hummetroth/kader/verein/6508', true),
('OBLC', '4929', 'SV Darmstadt 98 II', 'https://www.transfermarkt.de/sv-darmstadt-98-ii/kader/verein/4929', true),
('OBLC', '4900', 'FC Bayern Alzenau', 'https://www.transfermarkt.de/fc-bayern-alzenau/kader/verein/4900', true),
('OBLC', '2971', 'FC Eddersheim', 'https://www.transfermarkt.de/fc-eddersheim/kader/verein/2971', true),
('OBLC', '6273', 'TSV Eintracht Stadtallendorf', 'https://www.transfermarkt.de/eintracht-stadtallendorf/kader/verein/6273', true),
('OBLC', '66883', 'FC Gießen', 'https://www.transfermarkt.de/fc-giessen/kader/verein/66883', true),
('OBLC', '1315', 'KSV Baunatal', 'https://www.transfermarkt.de/ksv-baunatal/kader/verein/1315', true),
('OBLC', '7657', 'FC Turabdin-Babylon Pohlheim', 'https://www.transfermarkt.de/fc-tuba-pohlheim/kader/verein/7657', true),
('OBLC', '37387', 'Türk Gücü Friedberg', 'https://www.transfermarkt.de/turkgucu-friedberg/kader/verein/37387', true),
('OBLC', '1197', 'Hünfelder SV', 'https://www.transfermarkt.de/hunfelder-sv/kader/verein/1197', true),
('OBLC', '33308', 'Hanauer SC 1960', 'https://www.transfermarkt.de/hanauer-sc-1960/kader/verein/33308', true),
('OBLC', '7702', 'SV Rot-Weiss Walldorf', 'https://www.transfermarkt.de/sv-rot-weiss-walldorf/kader/verein/7702', true),
('OBLC', '1915', 'VfB Marburg', 'https://www.transfermarkt.de/vfb-marburg/kader/verein/1915', true),
('OBLC', '2266', 'FSV Fernwald', 'https://www.transfermarkt.de/fsv-fernwald/kader/verein/2266', true),
('OBLC', '21307', 'CSC 03 Kassel', 'https://www.transfermarkt.de/csc-03-kassel/kader/verein/21307', true),
('OBLC', '8048', 'KSV Hessen Kassel II', 'https://www.transfermarkt.de/ksv-hessen-kassel-ii/kader/verein/8048', true),
('OBLC', '36748', 'SV Rot-Weiß Hadamar', 'https://www.transfermarkt.de/sv-rot-weiss-hadamar/kader/verein/36748', true),
('OBLC', '11159', 'SV Unter-Flockenbach', 'https://www.transfermarkt.de/sv-unter-flockenbach/kader/verein/11159', true),
('OLMR', '21476', 'SC Fortuna Köln U23', 'https://www.transfermarkt.de/sc-fortuna-koln-u23/kader/verein/21476', true),
('OLMR', '46368', 'Eintracht Hohkeppel', 'https://www.transfermarkt.de/eintracht-hohkeppel/kader/verein/46368', true),
('OLMR', '6565', 'Siegburger SV 04', 'https://www.transfermarkt.de/siegburger-sv-04/kader/verein/6565', true),
('OLMR', '35313', 'SSV Merten 1925', 'https://www.transfermarkt.de/ssv-merten-1925/kader/verein/35313', true),
('OLMR', '38140', 'VfL Vichttal', 'https://www.transfermarkt.de/vfl-vichttal/kader/verein/38140', true),
('OLMR', '2681', 'FC Wegberg-Beeck', 'https://www.transfermarkt.de/fc-wegberg-beeck/kader/verein/2681', true),
('OLMR', '16711', 'SpVg Frechen 20', 'https://www.transfermarkt.de/spvg-frechen-20/kader/verein/16711', true),
('OLMR', '45330', 'SSV Bornheim 1924', 'https://www.transfermarkt.de/ssv-bornheim-1924/kader/verein/45330', true),
('OLMR', '40330', 'TuS Blau-Weiß Königsdorf', 'https://www.transfermarkt.de/tus-bw-konigsdorf/kader/verein/40330', true),
('OLMR', '67453', '1.FC Düren', 'https://www.transfermarkt.de/1-fc-duren/kader/verein/67453', true),
('OLMR', '15171', 'FC Hennef 05', 'https://www.transfermarkt.de/fc-hennef-05/kader/verein/15171', true),
('OLMR', '2527', 'SpVg Porz', 'https://www.transfermarkt.de/spvg-porz/kader/verein/2527', true),
('OLMR', '49947', 'FSV SW Neunkirchen-Seelscheid', 'https://www.transfermarkt.de/fsv-sw-neunkirchen-seelscheid/kader/verein/49947', true),
('OLMR', '32620', 'TuS Chlodwig Zülpich', 'https://www.transfermarkt.de/tus-chlodwig-zulpich/kader/verein/32620', true),
('OLMR', '5605', 'SC Borussia Lindenthal-Hohenlind', 'https://www.transfermarkt.de/sc-borussia-lindenthal-hohenlind/kader/verein/5605', true),
('OLMR', '9157', 'FC Hürth', 'https://www.transfermarkt.de/fc-hurth/kader/verein/9157', true),
('OLNI', '4690', 'Fortuna Düsseldorf II', 'https://www.transfermarkt.de/fortuna-dusseldorf-ii/kader/verein/4690', true),
('OLNI', '954', 'SSVg Velbert 02', 'https://www.transfermarkt.de/ssvg-velbert-02/kader/verein/954', true),
('OLNI', '299', 'Wuppertaler SV', 'https://www.transfermarkt.de/wuppertaler-sv/kader/verein/299', true),
('OLNI', '22009', 'Spvg. Solingen-Wald 03', 'https://www.transfermarkt.de/spvg-solingen-wald-03/kader/verein/22009', true),
('OLNI', '2530', 'Ratingen 04/19', 'https://www.transfermarkt.de/ratingen-04-19/kader/verein/2530', true),
('OLNI', '95', 'KFC Uerdingen 05', 'https://www.transfermarkt.de/kfc-uerdingen-05/kader/verein/95', true),
('OLNI', '2738', 'SpVg Schonnebeck', 'https://www.transfermarkt.de/spvg-schonnebeck/kader/verein/2738', true),
('OLNI', '42635', 'SC St. Tönis 1911/20', 'https://www.transfermarkt.de/djk-teutonia-st-tonis/kader/verein/42635', true),
('OLNI', '49126', 'TSV Meerbusch', 'https://www.transfermarkt.de/tsv-meerbusch/kader/verein/49126', true),
('OLNI', '28916', 'SV Blau-Weiß Dingden', 'https://www.transfermarkt.de/sv-blau-weiss-dingden/kader/verein/28916', true),
('OLNI', '47583', 'VfL Jüchen-Garzweiler', 'https://www.transfermarkt.de/vfl-juchen-garzweiler/kader/verein/47583', true),
('OLNI', '5328', 'SF Baumberg', 'https://www.transfermarkt.de/sf-baumberg/kader/verein/5328', true),
('OLNI', '463', 'Schwarz-Weiß Essen', 'https://www.transfermarkt.de/schwarz-weiss-essen/kader/verein/463', true),
('OLNI', '12719', '1.FC Monheim', 'https://www.transfermarkt.de/1-fc-monheim/kader/verein/12719', true),
('OLNI', '6311', 'SV Sonsbeck', 'https://www.transfermarkt.de/sv-sonsbeck/kader/verein/6311', true),
('OLNI', '17979', 'FC Büderich', 'https://www.transfermarkt.de/fc-buderich/kader/verein/17979', true),
('OLNI', '28006', 'Holzheimer SG', 'https://www.transfermarkt.de/holzheimer-sg/kader/verein/28006', true),
('OLNI', '42604', 'SV Scherpenberg', 'https://www.transfermarkt.de/sv-scherpenberg/kader/verein/42604', true),
('OBLN', '1212', 'Eintracht Braunschweig II', 'https://www.transfermarkt.de/eintracht-braunschweig-ii/kader/verein/1212', true),
('OBLN', '4883', 'Blau-Weiß Lohne', 'https://www.transfermarkt.de/blau-weiss-lohne/kader/verein/4883', true),
('OBLN', '10381', '1.FC Germania Egestorf/Langreder', 'https://www.transfermarkt.de/1-fc-germania-egestorf-langreder/kader/verein/10381', true),
('OBLN', '40505', 'Heeslinger SC', 'https://www.transfermarkt.de/heeslinger-sc/kader/verein/40505', true),
('OBLN', '2540', 'VfV Borussia 06 Hildesheim', 'https://www.transfermarkt.de/vfv-borussia-06-hildesheim/kader/verein/2540', true),
('OBLN', '96', 'SV Wilhelmshaven', 'https://www.transfermarkt.de/sv-wilhelmshaven/kader/verein/96', true),
('OBLN', '18324', 'Lüneburger SK Hansa', 'https://www.transfermarkt.de/luneburger-sk-hansa/kader/verein/18324', true),
('OBLN', '2106', 'SC Spelle-Venhaus', 'https://www.transfermarkt.de/sc-spelle-venhaus/kader/verein/2106', true),
('OBLN', '7430', 'SV Meppen II', 'https://www.transfermarkt.de/sv-meppen-ii/kader/verein/7430', true),
('OBLN', '18603', 'TuS Bersenbrück', 'https://www.transfermarkt.de/tus-bersenbruck/kader/verein/18603', true),
('OBLN', '5560', 'BSV Schwarz-Weiß Rehden', 'https://www.transfermarkt.de/bsv-schwarz-weiss-rehden/kader/verein/5560', true),
('OBLN', '18427', 'FC Verden 04', 'https://www.transfermarkt.de/fc-verden-04/kader/verein/18427', true),
('OBLN', '19295', 'SV Drochtersen/Assel II', 'https://www.transfermarkt.de/sv-drochtersen-assel-ii/kader/verein/19295', true),
('OBLN', '38960', 'SC Hemmingen-Westerfeld', 'https://www.transfermarkt.de/sc-hemmingen-westerfeld/kader/verein/38960', true),
('OBLN', '6243', 'Vorwärts Nordhorn', 'https://www.transfermarkt.de/vorwarts-nordhorn/kader/verein/6243', true),
('OBLN', '2541', 'SSV Vorsfelde', 'https://www.transfermarkt.de/ssv-vorsfelde/kader/verein/2541', true),
('OBLF', '2943', 'FC Hertha 03 Zehlendorf', 'https://www.transfermarkt.de/fc-hertha-03-zehlendorf/kader/verein/2943', true),
('OBLF', '584', 'Berliner AK 07', 'https://www.transfermarkt.de/berliner-ak-07/kader/verein/584', true),
('OBLF', '1333', 'SV Lichtenberg 47', 'https://www.transfermarkt.de/sv-lichtenberg-47/kader/verein/1333', true),
('OBLF', '402', 'FC Hansa Rostock II', 'https://www.transfermarkt.de/fc-hansa-rostock-ii/kader/verein/402', true),
('OBLF', '1151', 'TSG Neustrelitz', 'https://www.transfermarkt.de/tsg-neustrelitz/kader/verein/1151', true),
('OBLF', '7317', 'Union Klosterfelde', 'https://www.transfermarkt.de/union-klosterfelde/kader/verein/7317', true),
('OBLF', '42641', 'SV Siedenbollentin', 'https://www.transfermarkt.de/sv-siedenbollentin/kader/verein/42641', true),
('OBLF', '7651', 'Eintracht Mahlsdorf', 'https://www.transfermarkt.de/eintracht-mahlsdorf/kader/verein/7651', true),
('OBLF', '5008', 'TuS Makkabi Berlin', 'https://www.transfermarkt.de/tus-makkabi-berlin/kader/verein/5008', true),
('OBLF', '3676', 'FC Anker Wismar', 'https://www.transfermarkt.de/fc-anker-wismar/kader/verein/3676', true),
('OBLF', '6812', 'SV Sparta Lichtenberg', 'https://www.transfermarkt.de/sv-sparta-lichtenberg/kader/verein/6812', true),
('OBLF', '562', 'FSV Optik Rathenow', 'https://www.transfermarkt.de/fsv-optik-rathenow/kader/verein/562', true),
('OBLF', '101', 'Tennis Borussia Berlin', 'https://www.transfermarkt.de/tennis-borussia-berlin/kader/verein/101', true),
('OBLF', '4043', '1.FC Lok Stendal', 'https://www.transfermarkt.de/1-fc-lok-stendal/kader/verein/4043', true),
('OBLF', '217', 'Füchse Berlin Reinickendorf', 'https://www.transfermarkt.de/reinickendorfer-fuchse/kader/verein/217', true),
('OBLF', '40629', 'FC Mecklenburg Schwerin', 'https://www.transfermarkt.de/fc-mecklenburg-schwerin/kader/verein/40629', true),
('OBLG', '4825', 'FC Eilenburg', 'https://www.transfermarkt.de/fc-eilenburg/kader/verein/4825', true),
('OBLG', '41705', 'VfB Empor Glauchau', 'https://www.transfermarkt.de/vfb-empor-glauchau/kader/verein/41705', true),
('OBLG', '2643', 'ZFC Meuselwitz', 'https://www.transfermarkt.de/zfc-meuselwitz/kader/verein/2643', true),
('OBLG', '83553', 'SC Freital', 'https://www.transfermarkt.de/sc-freital/kader/verein/83553', true),
('OBLG', '391', 'VFC Plauen', 'https://www.transfermarkt.de/vfc-plauen/kader/verein/391', true),
('OBLG', '1400', 'VfB Auerbach', 'https://www.transfermarkt.de/vfb-auerbach/kader/verein/1400', true),
('OBLG', '364', 'Germania Halberstadt', 'https://www.transfermarkt.de/germania-halberstadt/kader/verein/364', true),
('OBLG', '910', 'VfL Halle 1896', 'https://www.transfermarkt.de/vfl-halle-1896/kader/verein/910', true),
('OBLG', '1412', 'FSV Budissa Bautzen', 'https://www.transfermarkt.de/budissa-bautzen/kader/verein/1412', true),
('OBLG', '20685', 'VfB 1921 Krieschow', 'https://www.transfermarkt.de/vfb-1921-krieschow/kader/verein/20685', true),
('OBLG', '2665', 'Union Sandersdorf', 'https://www.transfermarkt.de/union-sandersdorf/kader/verein/2665', true),
('OBLG', '7021', 'Einheit Wernigerode', 'https://www.transfermarkt.de/einheit-wernigerode/kader/verein/7021', true),
('OBLG', '4219', 'FC Einheit Rudolstadt', 'https://www.transfermarkt.de/fc-einheit-rudolstadt/kader/verein/4219', true),
('OBLG', '706', '1.FC Frankfurt (Oder)', 'https://www.transfermarkt.de/1-fc-frankfurt-oder-/kader/verein/706', true),
('OBLG', '5083', 'Dynamo Dresden II', 'https://www.transfermarkt.de/dynamo-dresden-ii/kader/verein/5083', true),
('OBLG', '69235', 'SSC Weißenfels', 'https://www.transfermarkt.de/ssc-weissenfels/kader/verein/69235', true),
('OLRP', '9695', 'TSV Schott Mainz', 'https://www.transfermarkt.de/tsv-schott-mainz/kader/verein/9695', true),
('OLRP', '5406', 'SV 07 Elversberg II', 'https://www.transfermarkt.de/sv-07-elversberg-ii/kader/verein/5406', true),
('OLRP', '131473', 'FC Emmelshausen-Karbach', 'https://www.transfermarkt.de/fc-emmelshausen-karbach/kader/verein/131473', true),
('OLRP', '158', 'VfR Wormatia Worms', 'https://www.transfermarkt.de/vfr-wormatia-worms/kader/verein/158', true),
('OLRP', '726', 'FK Pirmasens', 'https://www.transfermarkt.de/fk-pirmasens/kader/verein/726', true),
('OLRP', '996', 'TuS Koblenz', 'https://www.transfermarkt.de/tus-koblenz/kader/verein/996', true),
('OLRP', '2085', 'FV Engers 07', 'https://www.transfermarkt.de/fv-engers-07/kader/verein/2085', true),
('OLRP', '22327', 'FC Rot-Weiss Koblenz', 'https://www.transfermarkt.de/tus-rot-weiss-koblenz/kader/verein/22327', true),
('OLRP', '6855', 'FC Hertha Wiesbach', 'https://www.transfermarkt.de/fc-hertha-wiesbach/kader/verein/6855', true),
('OLRP', '54310', 'TSV Gau-Odernheim', 'https://www.transfermarkt.de/tsv-gau-odernheim/kader/verein/54310', true),
('OLRP', '45062', 'FC Cosmos Koblenz', 'https://www.transfermarkt.de/fc-cosmos-koblenz/kader/verein/45062', true),
('OLRP', '6871', 'SV Gonsenheim', 'https://www.transfermarkt.de/sv-gonsenheim/kader/verein/6871', true),
('OLRP', '6482', 'SV Auersmacher', 'https://www.transfermarkt.de/sv-auersmacher/kader/verein/6482', true),
('OLRP', '11345', 'FV 07 Diefflen', 'https://www.transfermarkt.de/fv-07-diefflen/kader/verein/11345', true),
('OLRP', '1206', 'Sportfreunde Eisbachtal', 'https://www.transfermarkt.de/sportfreunde-eisbachtal/kader/verein/1206', true),
('OLRP', '2594', 'TuS Mechtersheim', 'https://www.transfermarkt.de/tus-mechtersheim/kader/verein/2594', true),
('OLRP', '25210', 'Ahrweiler BC', 'https://www.transfermarkt.de/ahrweiler-bc/kader/verein/25210', true),
('OLRP', '40086', 'SV Rot-Weiss Wittlich', 'https://www.transfermarkt.de/sv-rot-weiss-wittlich/kader/verein/40086', true),
('OBLL', '1171', 'Holstein Kiel II', 'https://www.transfermarkt.de/holstein-kiel-ii/kader/verein/1171', true),
('OBLL', '5558', 'FC Kilia Kiel', 'https://www.transfermarkt.de/fc-kilia-kiel/kader/verein/5558', true),
('OBLL', '4882', 'SV Eichede', 'https://www.transfermarkt.de/sv-eichede/kader/verein/4882', true),
('OBLL', '912', 'VfR Neumünster', 'https://www.transfermarkt.de/vfr-neumunster/kader/verein/912', true),
('OBLL', '1297', 'Heider SV', 'https://www.transfermarkt.de/heider-sv/kader/verein/1297', true),
('OBLL', '2382', 'PSV Union Neumünster', 'https://www.transfermarkt.de/psv-union-neumunster/kader/verein/2382', true),
('OBLL', '48987', '1.FC Phönix Lübeck II', 'https://www.transfermarkt.de/1-fc-phonix-lubeck-ii/kader/verein/48987', true),
('OBLL', '18734', 'TSV Nordmark Satrup', 'https://www.transfermarkt.de/tsv-nordmark-satrup/kader/verein/18734', true),
('OBLL', '19276', 'Kaltenkirchener TS', 'https://www.transfermarkt.de/kaltenkirchener-ts/kader/verein/19276', true),
('OBLL', '21107', 'TuS Rotenhof', 'https://www.transfermarkt.de/tus-rotenhof/kader/verein/21107', true),
('OBLL', '8812', 'MTSV Hohenwestedt', 'https://www.transfermarkt.de/mtsv-hohenwestedt/kader/verein/8812', true),
('OBLL', '4877', 'Oldenburger SV', 'https://www.transfermarkt.de/oldenburger-sv/kader/verein/4877', true),
('OBLL', '25155', 'SC Rapid Lübeck', 'https://www.transfermarkt.de/sc-rapid-lubeck/kader/verein/25155', true),
('OBLL', '3400', 'TSB Flensburg', 'https://www.transfermarkt.de/tsb-flensburg/kader/verein/3400', true),
('OBLL', '18330', 'Eckernförder SV', 'https://www.transfermarkt.de/eckernforder-sv/kader/verein/18330', true),
('OBLL', '3322', 'VfB Lübeck II', 'https://www.transfermarkt.de/vfb-lubeck-ii/kader/verein/3322', true),
('OLW3', '831', 'Arminia Bielefeld II', 'https://www.transfermarkt.de/arminia-bielefeld-ii/kader/verein/831', true),
('OLW3', '10193', 'ASC 09 Dortmund', 'https://www.transfermarkt.de/asc-09-dortmund/kader/verein/10193', true),
('OLW3', '767', 'SV Lippstadt 08', 'https://www.transfermarkt.de/sv-lippstadt-08/kader/verein/767', true),
('OLW3', '7019', 'Preußen Münster II', 'https://www.transfermarkt.de/preussen-munster-ii/kader/verein/7019', true),
('OLW3', '4618', '1.FC Gievenbeck', 'https://www.transfermarkt.de/1-fc-gievenbeck/kader/verein/4618', true),
('OLW3', '2188', 'Victoria Clarholz', 'https://www.transfermarkt.de/victoria-clarholz/kader/verein/2188', true),
('OLW3', '7251', 'SC Verl II', 'https://www.transfermarkt.de/sc-verl-ii/kader/verein/7251', true),
('OLW3', '1137', 'FC Eintracht Rheine', 'https://www.transfermarkt.de/fc-eintracht-rheine/kader/verein/1137', true),
('OLW3', '2508', 'SV Schermbeck', 'https://www.transfermarkt.de/sv-schermbeck/kader/verein/2508', true),
('OLW3', '1000', 'TSG Sprockhövel', 'https://www.transfermarkt.de/tsg-sprockhovel/kader/verein/1000', true),
('OLW3', '1459', 'SpVgg Erkenschwick', 'https://www.transfermarkt.de/spvgg-erkenschwick/kader/verein/1459', true),
('OLW3', '1048', 'SpVgg Vreden', 'https://www.transfermarkt.de/spvgg-vreden/kader/verein/1048', true),
('OLW3', '8712', 'TuS Ennepetal', 'https://www.transfermarkt.de/tus-ennepetal/kader/verein/8712', true),
('OLW3', '9553', 'TuS Hiltrup', 'https://www.transfermarkt.de/tus-hiltrup/kader/verein/9553', true),
('OLW3', '909', 'SC Rot-Weiß Maaslingen', 'https://www.transfermarkt.de/sc-rot-weiss-maaslingen/kader/verein/909', true),
('OLW3', '1619', 'DJK TuS Hordel', 'https://www.transfermarkt.de/djk-tus-hordel/kader/verein/1619', true),
('OLW3', '2211', 'Westfalia Kinderhaus', 'https://www.transfermarkt.de/westfalia-kinderhaus/kader/verein/2211', true),
('OLW3', '37249', 'SpVgg Horsthausen', 'https://www.transfermarkt.de/spvgg-horsthausen/kader/verein/37249', true)
ON CONFLICT (tm_club_id) DO UPDATE SET league_id = EXCLUDED.league_id, club_name = EXCLUDED.club_name, tm_squad_url = EXCLUDED.tm_squad_url, is_active = true, updated_at = NOW();
